/*
 * Copyright 2018, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.android.trackmysleepquality.database

import android.content.Context
import androidx.room.*

@Database (entities = [SleepNight::class], version = 1, exportSchema = false)
abstract class SleepDatabase : RoomDatabase() {

        abstract val sleepDatabaseDao: SleepDatabaseDao

        companion object {
                @Volatile
                private var INSTANCE: SleepDatabase? = null

                fun getInstance(context: Context) : SleepDatabase {
                        synchronized (this) {
                                // we need a local variable to be able to use Kotlin's smart cast
                                var instance = INSTANCE

                                if (instance == null) {
                                        instance = Room.databaseBuilder(
                                                context.applicationContext,
                                                SleepDatabase::class.java,
                                                "sleep_history_database"
                                        )
                                                .fallbackToDestructiveMigration()
                                                .build()
                                }

                                return instance
                        }
                }
        }

}


@Entity (tableName = "daily_sleep_quality_table")
data class SleepNight (
        @PrimaryKey (autoGenerate = true) @ColumnInfo (name = "night_id")
        var nightId : Long = 0L,        // must be Long since it will be autogenerated

        @ColumnInfo (name = "start_time_millis")
        var startTimeMillis : Long = System.currentTimeMillis(),

        @ColumnInfo (name = "end_time_millis")
        var endTimeMillis : Long = startTimeMillis,

        @ColumnInfo (name = "quality_rating")
        var sleepQuality : Int = -1
)